#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 24 09:26:33 2021

@author: shipe
"""


import obspy
import os
import sys
sys.path.append('/home/shipe/codes/MALMI/src')
from ioformatting import stream2EQTinput, stainv2json
from EQTransformer.utils.hdf5_maker import preprocessor
from EQTransformer.core.predictor import predictor


# %% (1) read in seismic data as obspy stream and output to the data format that QET can handle
dir_input = "../data/seismic_data/arclink_original/20201025/"  # directory to seismic data
mseed_dir = "../data/seismic_data/EQT/mseeds"  # directory for outputting seismic data for EQT

file_seismicin = sorted([fname for fname in os.listdir(dir_input) if os.path.isfile(os.path.join(dir_input, fname))])
stream = obspy.Stream()
for dfile in file_seismicin:
    stream += obspy.read(os.path.join(dir_input, dfile))

stream2EQTinput(stream, mseed_dir)


# %% (2) create station jason file for EQT
file_station = '../data/station/Package_1624564133765_0.xml'  # station metadata file, in FDSNWS station text format: *.txt or StationXML format: *.xml
dir_json = "../data/seismic_data/EQT/json"  # directory for outputting station json file
stainv2json(file_station, mseed_dir, dir_json)


# %% (3) create hdf5 data for EQT inputs
stations_json = dir_json + "/station_list.json"  # station JSON file
overlap = 0.5  # overlap rate of time window. e.g. 0.6 means 60% of time window are overlapped
n_processor = 1  # number of CPU processors for parallel preprocessing and producing hdf5 data
preproc_dir = "../data/seismic_data/EQT/preproc_overlap{}".format(overlap)  # path of the directory where will be located the summary files generated by preprocessor step

preprocessor(preproc_dir=preproc_dir, mseed_dir=mseed_dir, 
             stations_json=stations_json, overlap=overlap, 
             n_processor=n_processor)


# %% (4) perform detection and picking and output probabilities and figures
input_dir = mseed_dir + '_processed_hdfs'  # path to the hdf5 and csv files
input_model = '/home/shipe/codes/EQTransformer/ModelsAndSampleData/EqT_model.h5'  # path to a trained EQT model
output_dir = '../data/seismic_data/EQT/detections_model'  # output directory

predictor(input_dir=input_dir, input_model=input_model, output_dir=output_dir,
          output_probabilities=True, estimate_uncertainty=True,
          detection_threshold=0.3, P_threshold=0.1, S_threshold=0.1, 
          keepPS=False, number_of_cpus=1,
          number_of_plots=100, plot_mode='time_frequency')




